name: Update gist with WakaTime stats

on:
  push:
    branches: 
      - master
  schedule:
    - cron: "*/10 * * * *"
    

jobs:

  build:
    name: Upddate-gist
    runs-on: ubuntu-latest
    env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 6062fa5e7c542b506402103540ae8b7f
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Update-gist
      run: |-
          git clone https://github.com/YouEclipse/waka-box-go.git 
          cd waka-box-go && go build -o waka ./cmd/box/main.go
          mv ./waka ../ && cd .. && rm -rf waka-box-go/

    - name: Commit and push
      run: |-
        ./waka